all: fputmake fgetmake listmake do_execmake getaclmake setaclmake create_dirmake cdirmake
fputmake: fput.cpp
			g++ fput.cpp -o fput
fgetmake: fget.cpp
			g++ fget.cpp -o fget
listmake: list.cpp
			g++ list.cpp -o list
do_execmake: do_exec.cpp
			g++ do_exec.cpp -o do_exec
getaclmake: getacl.cpp
			g++ getacl.cpp -o getacl
setaclmake: setacl.cpp
			g++ setacl.cpp -o setacl
create_dirmake: create_dir.cpp
			g++ create_dir.cpp -o create_dir
cdirmake: cdir.cpp
			g++ cdir.cpp -o cdir
